name: Codecov

on:
  push:
    branches: [ codecov ]
  workflow_dispatch:

jobs:
  code-coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: sudo apt install lcov && cd src && make -f Makefile.linux-x86.mk coverage
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -f src/coverage/coverage-clean.info -t ${{ secrets.CODECOV_TOKEN }} || echo "Codecov did not collect coverage reports"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: src/coverage/
